version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: healthseller
      POSTGRES_PASSWORD: 123
    network_mode: "host"

  adminer:
    image: adminer
    restart: always
    ports:
      - 5433:5433